debug: true
server:
  port: 8098
  tomcat:
    accept-count: 3000
    uri-encoding: UTF-8
    min-spare-threads: 200
    max-threads: 2000
  ssl:
    enabled: false
spring:
  profiles:
    active: dev
druid:
    type: com.alibaba.druid.pool.DruidDataSource
    datasource:
        mapperLocations: "classpath:/mapper/*/*/*.xml"
    study:
      master: #study库的主库
        url: jdbc:mysql://127.0.0.1:3306/study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: Welcome1
        initial-size: 5
        min-idle: 1
        max-active: 20
        test-on-borrow: true
        mapperlacation: "classpath:/mapper/study/master/*.xml"
      slave: #study库的从库
        url: jdbc:mysql://127.0.0.1:3306/study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: Welcome1
        initial-size: 5
        min-idle: 1
        max-active: 20
        test-on-borrow: true
        mapperlacation: "classpath:/mapper/study/slave/*.xml"
    product:
      master: #product库的主库
        url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: Welcome1
        initial-size: 5
        min-idle: 1
        max-active: 20
        test-on-borrow: true
      slave: #product库的从库
        url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: Welcome1
        initial-size: 5
        min-idle: 1
        max-active: 20
        test-on-borrow: true
mybatis:
  configuration:
    #数据库超过180秒仍未响应则超时 sql执行时间,单位秒
    default-statement-timeout:  180
    cache-enabled: true
    # 查询时，关闭关联对象即时加载以提高性能 默认false
    lazy-loading-enabled: true
    #设置关联对象加载的形态，此处为按需加载字段(加载字段由SQL指 定)，不会加载关联表的所有字段，以提高性能 默认true
    aggressive-lazy-loading: true
    #对于未知的SQL查询，允许返回不同的结果集以达到通用的效果 默认 true
    multiple-result-sets-enabled: true
     #允许使用列标签代替列名 默认 true
    use-column-label: true
    #给予被嵌套的resultMap以字段-属性的映射支持
    auto-mapping-behavior: PARTIAL
    # 不打印sql执行日志
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl