druid:
    type: com.alibaba.druid.pool.DruidDataSource
    study:
      master: #study库的主库
        url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Welcome1
        initial-size: 5
        min-idle: 1
        max-active: 20
        test-on-borrow: true
      slave: #study库的从库
        url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Welcome1
        initial-size: 5
        min-idle: 1
        max-active: 20
        test-on-borrow: true
    product:
      master: #product库的主库
        url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Welcome1
        initial-size: 5
        min-idle: 1
        max-active: 20
        test-on-borrow: true
      slave: #product库的从库
        url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Welcome1
        initial-size: 5
        min-idle: 1
        max-active: 20
        test-on-borrow: true